dataloading:
  batchsize: 1
  cache_fields: true
  classes: '[broom]'
  dataset_name: DTU
  ignore_image_idx: []
  img_size: null
  n_views: 101
  n_workers: 8
  path: data/DIY/
model:
  warp: 0
  feat_size: 256
  geometric_init: true
  hidden_dim: 256
  num_layers: 8
  octaves_pe: 6
  octaves_pe_views: 4
  octaves_pe_warp: 6
  rescale: 1.0
  sig_factor: 10.0
  skips:
  - 4
rendering:
  interval_decay: 1.5e-05
  interval_end: 0.1
  interval_start: 2.0
  n_max_network_queries: 64000
  num_points_in: 64
  num_points_out: 32
  occ_prob_points: 64
  radius: 4.0
  ray_marching_steps: 256
  sig_factor: 10.0
  type: unisurf
  white_background: false
training:
  backup_every: 10000
  batch_size: 1
  checkpoint_every: 5000
  lambda_l1_rgb: 1.0
  lambda_normals: 0.005
  lambda_occ_prob: 0.0
  learning_rate: 0.0001
  n_training_points: 1024
  out_dir: ./out/DIY/broom/
  print_every: 100
  scheduler_gamma: 0.5
  scheduler_milestones: '[4000, 8000]'
  type: unisurf
  vis_resolution: '[536, 960]'
  visualize_every: 1000
  visualize_skip: 20
  weight_decay: 0.0
